#!/bin/bash
set -Eeuo pipefail

# ==========================================================
# MDC Rocky Linux 9.6 Common Initial Configuration
#
# File   : mdc-common-init.sh
# Usage  : ./mdc-common-init.sh <hostname>
# Example: ./mdc-common-init.sh ctrl02
#
# Optional environment variables:
#   DNS1=8.8.8.8
#   DNS2=1.1.1.1
# ==========================================================

SCRIPT_VERSION="1.0.0"
NEW_HOSTNAME="${1:-}"
DNS1="${DNS1:-8.8.8.8}"
DNS2="${DNS2:-1.1.1.1}"

die() {
    echo "[ERROR] $*" >&2
    exit 1
}

log() {
    echo "[INFO] $*"
}

if [[ -z "${NEW_HOSTNAME}" ]]; then
    echo "Usage  : $0 <hostname>"
    echo "Example: $0 ctrl02"
    exit 1
fi

if [[ "$(id -u)" -ne 0 ]]; then
    die "root 계정으로 실행해야 합니다."
fi

if [[ ! "${NEW_HOSTNAME}" =~ ^[a-zA-Z0-9][a-zA-Z0-9-]{0,62}$ ]]; then
    die "유효하지 않은 hostname 형식입니다: ${NEW_HOSTNAME}"
fi

for cmd in hostnamectl ip awk nmcli sed grep ping getent dnf timedatectl systemctl; do
    command -v "${cmd}" >/dev/null 2>&1 || die "필수 명령어가 없습니다: ${cmd}"
done

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
BACKUP_DIR="/root/mdc-backup-${TIMESTAMP}"

trap 'echo "[ERROR] line=${LINENO}, command=${BASH_COMMAND}" >&2' ERR

echo
echo "======================================================"
echo " MDC COMMON INITIAL SETUP"
echo " Version         : ${SCRIPT_VERSION}"
echo " Target Hostname : ${NEW_HOSTNAME}"
echo " Start Time      : $(date)"
echo "======================================================"

echo
echo "[1/9] OS Check"
[[ -f /etc/rocky-release ]] || die "Rocky Linux가 아닙니다."
cat /etc/rocky-release

if ! grep -q "^Rocky Linux release 9\.6" /etc/rocky-release; then
    die "Rocky Linux 9.6이 아닙니다. 작업을 중지합니다."
fi
echo "[OK] Rocky Linux 9.6"

echo
echo "[2/9] Management Network Detection"

MGMT_IF="$(ip -4 route show default | awk 'NR==1 {print $5}')"
GATEWAY="$(ip -4 route show default | awk 'NR==1 {print $3}')"

[[ -n "${MGMT_IF}" ]] || die "Default Route의 NIC를 찾지 못했습니다."
[[ -n "${GATEWAY}" ]] || die "Default Gateway를 찾지 못했습니다."

CON_NAME="$(nmcli -g GENERAL.CONNECTION device show "${MGMT_IF}" | head -1)"
[[ -n "${CON_NAME}" && "${CON_NAME}" != "--" ]] || die "NetworkManager Connection을 찾지 못했습니다."

MGMT_IP="$(ip -4 addr show dev "${MGMT_IF}" | awk '/inet / {print $2}' | cut -d/ -f1 | head -1)"
[[ -n "${MGMT_IP}" ]] || die "Management IP를 찾지 못했습니다."

echo "Management NIC : ${MGMT_IF}"
echo "Connection     : ${CON_NAME}"
echo "Management IP  : ${MGMT_IP}"
echo "Gateway        : ${GATEWAY}"

echo
echo "[3/9] Configuration Backup"

mkdir -p "${BACKUP_DIR}"
cp -p /etc/hosts "${BACKUP_DIR}/hosts" 2>/dev/null || true

if [[ -e /etc/resolv.conf ]]; then
    cp -a /etc/resolv.conf "${BACKUP_DIR}/resolv.conf" || true
fi

if [[ -d /etc/NetworkManager/system-connections ]]; then
    cp -a /etc/NetworkManager/system-connections "${BACKUP_DIR}/" || true
fi

echo "[OK] Backup : ${BACKUP_DIR}"

echo
echo "[4/9] Hostname Configuration"

OLD_HOSTNAME="$(hostname)"
hostnamectl set-hostname "${NEW_HOSTNAME}"

echo "Old Hostname : ${OLD_HOSTNAME}"
echo "New Hostname : $(hostname)"

echo
echo "[5/9] /etc/hosts Configuration"

sed -i "\|^${MGMT_IP}[[:space:]]|d" /etc/hosts
echo "${MGMT_IP}    ${NEW_HOSTNAME}" >> /etc/hosts

echo
echo "--- /etc/hosts ---"
cat /etc/hosts

echo
echo "[6/9] DNS Configuration"

nmcli connection modify "${CON_NAME}" ipv4.dns "${DNS1},${DNS2}"
nmcli connection modify "${CON_NAME}" ipv4.ignore-auto-dns yes

nmcli connection reload
nmcli device reapply "${MGMT_IF}" || true
systemctl reload NetworkManager || true
sleep 2

if [[ ! -s /etc/resolv.conf ]] || ! grep -q '^nameserver ' /etc/resolv.conf 2>/dev/null; then
    log "/etc/resolv.conf에 nameserver가 없어 fallback DNS 파일을 생성합니다."
    cat > /etc/resolv.conf <<RESOLV
# Generated by mdc-common-init.sh
nameserver ${DNS1}
nameserver ${DNS2}
RESOLV
fi

echo
echo "--- Connection DNS ---"
nmcli connection show "${CON_NAME}" | egrep 'ipv4.dns:|ipv4.ignore-auto-dns' || true

echo
echo "--- Active DNS ---"
nmcli -f GENERAL.CONNECTION,IP4.DNS device show "${MGMT_IF}" || true

echo
echo "--- /etc/resolv.conf ---"
cat /etc/resolv.conf 2>/dev/null || true

echo
echo "[7/9] Time / NTP Check"

timedatectl | egrep 'Local time|Time zone|System clock synchronized|NTP service' || true

if systemctl is-active --quiet chronyd; then
    echo "[OK] chronyd active"
else
    echo "[WARNING] chronyd not active"
fi

if command -v chronyc >/dev/null 2>&1; then
    chronyc tracking 2>/dev/null | egrep 'Stratum|System time|Leap status' || true
fi

echo
echo "[8/9] Network Validation"

echo
echo "--- Hostname ---"
hostname

echo
echo "--- Management ---"
ip -br addr show "${MGMT_IF}"

echo
echo "--- Route ---"
ip route

echo
echo "--- Local Hostname Resolution ---"
getent ahostsv4 "${NEW_HOSTNAME}" | head -1 || true

echo
echo "--- Gateway Test ---"
if ping -c 1 -W 2 "${GATEWAY}" >/dev/null 2>&1; then
    echo "[OK] Gateway ${GATEWAY}"
else
    echo "[FAIL] Gateway ${GATEWAY}"
fi

echo
echo "--- Internet IP Test ---"
if ping -c 1 -W 2 "${DNS1}" >/dev/null 2>&1; then
    echo "[OK] Internet IP"
else
    echo "[FAIL] Internet IP"
fi

echo
echo "--- DNS Test ---"
if getent hosts mirrors.rockylinux.org >/dev/null 2>&1; then
    echo "[OK] DNS resolution"
    getent hosts mirrors.rockylinux.org | head -2
else
    echo "[FAIL] DNS resolution"
fi

echo
echo "[9/9] DNF Repository Check"

dnf repolist || true

if dnf makecache >/tmp/mdc-dnf-makecache.log 2>&1; then
    echo "[OK] DNF makecache"
else
    echo "[WARNING] DNF makecache failed"
    tail -20 /tmp/mdc-dnf-makecache.log
fi

echo
echo "======================================================"
echo " MDC COMMON SETUP RESULT"
echo "======================================================"
echo "Hostname       : $(hostname)"
echo "OS             : $(cat /etc/rocky-release)"
echo "Management NIC : ${MGMT_IF}"
echo "Management IP  : ${MGMT_IP}"
echo "Gateway        : ${GATEWAY}"
echo "DNS            : ${DNS1}, ${DNS2}"
echo "Backup         : ${BACKUP_DIR}"
echo "======================================================"
echo "Completed      : $(date)"
echo "======================================================"
